---
on:
  push:
    branches:
      - master
  create:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2.6.1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_TOKEN }}
          registry: ghcr.io
          repository: ${{ github.repository }}
          tag_with_ref: true
